# Generated by Django 3.2.4 on 2021-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_rate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='percent_change_24h',
            field=models.FloatField(null=True),
        ),
    ]
