# Generated by Django 3.2.4 on 2021-06-18 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20210616_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserProfile',
        ),
    ]
